
from dataclasses import dataclass
from ct.objects.discordobject import DiscordObject

@dataclass
class Message(DiscordObject):
   id: Snowflake # id of the message
   channel_id: Snowflake # id of the channel the message was sent in
   guild_id_: Snowflake # id of the guild the message was sent in
   author*:   # the author of this message (not guaranteed to be a valid user, see below)
   member_**:   # member properties for this message's author
   content: str = "" # contents of the message
   timestamp: Iso8601 timestamp # when this message was sent
   edited_timestamp: Iso8601 timestamp # when this message was edited (or null if never)
   tts: bool = False # whether this was a TTS message
   mention_everyone: bool = False # whether this message mentions everyone
   mentions***:   # users specifically mentioned in the message
   mention_roles:   # roles specifically mentioned in this message
   mention_channels_****:   # channels specifically mentioned in this message
   attachments:   # any attached files
   embeds:   # any embedded content
   reactions_:   # reactions to the message
   nonce_: Integer or string # used for validating a message was sent
   pinned: bool = False # whether this message is pinned
   webhook_id_: Snowflake # if the message is generated by a webhook, this is the webhook's id
   type: int = -1 # type of message
   activity_:   # sent with Rich Presence-related chat embeds
   application_:   # sent with Rich Presence-related chat embeds
   message_reference_:   # reference data sent with crossposted messages
   flags_: int = -1 #  

